services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\ExtendedSchemaCommons\StateServices\ObjectResolvedDynamicVariablesServiceInterface:
        class: \PoPSchema\ExtendedSchemaCommons\StateServices\ObjectResolvedDynamicVariablesService

    PoPSchema\ExtendedSchemaCommons\FeedbackItemProviders\:
        resource: '../src/FeedbackItemProviders/*'
