services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    PoPSchema\ExtendedSchemaCommons\HelperServices\ArrayTraversionHelperServiceInterface:
        class: \PoPSchema\ExtendedSchemaCommons\HelperServices\ArrayTraversionHelperService
